/**
 * XState v5 runtime validation tests.
 *
 * Takes configs generated by our Python converter and validates them
 * through actual XState v5 createMachine() + createActor().
 */
import { readFileSync } from "fs";
import { createMachine, createActor, and, or, not } from "xstate";

const configs = JSON.parse(readFileSync(new URL("./configs.json", import.meta.url), "utf-8"));

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    console.log(`  \u2713 ${name}`);
  } catch (e) {
    failed++;
    console.log(`  \u2717 ${name}: ${e.message}`);
  }
}

function assert(condition, msg) {
  if (!condition) throw new Error(msg || "Assertion failed");
}

function assertEqual(a, b, msg) {
  const sa = JSON.stringify(a);
  const sb = JSON.stringify(b);
  if (sa !== sb) throw new Error(msg || `Expected ${sb}, got ${sa}`);
}

// Builds a machine from our config, supplying stubs for all referenced
// actions/guards/actors so createMachine doesn't throw on missing refs.
function buildMachine(entry) {
  const { setup: setupDef, config } = entry;

  const setupObj = {};

  if (setupDef.actions) {
    setupObj.actions = {};
    for (const name of Object.keys(setupDef.actions)) {
      setupObj.actions[name] = () => {};
    }
  }

  if (setupDef.guards) {
    setupObj.guards = {};
    for (const name of Object.keys(setupDef.guards)) {
      setupObj.guards[name] = () => true;
    }
  }

  if (setupDef.actors) {
    setupObj.actors = {};
    for (const name of Object.keys(setupDef.actors)) {
      // Stub actor as a promise that never resolves (invoke won't crash)
      setupObj.actors[name] = fromPromiseStub;
    }
  }

  // XState v5: setup().createMachine()
  // We need to use the imperative approach since setup is dynamic
  const machine = createMachine(
    {
      ...config,
      // Merge any string-based context into actual object if possible
      context: typeof config.context === "string" ? {} : (config.context || {}),
    },
    {
      actions: setupObj.actions || {},
      guards: setupObj.guards || {},
      actors: setupObj.actors || {},
    }
  );

  return machine;
}

// Stub for invoked actors — a promise-based actor logic
import { fromPromise } from "xstate";
const fromPromiseStub = fromPromise(() => new Promise(() => {}));

// ─── Tests ───────────────────────────────────────────────────────

console.log("\nXState v5 runtime validation\n");

// 1. All configs create valid machines
console.log("Machine creation:");
const machines = {};
for (const [name, entry] of Object.entries(configs)) {
  test(`createMachine(${name})`, () => {
    machines[name] = buildMachine(entry);
    assert(machines[name], "Machine should be created");
  });
}

// 2. All machines can start actors
console.log("\nActor creation:");
const actors = {};
for (const [name, machine] of Object.entries(machines)) {
  test(`createActor(${name}).start()`, () => {
    const actor = createActor(machine);
    actor.start();
    actors[name] = actor;
    assert(actor.getSnapshot(), "Actor should have a snapshot");
  });
}

// 3. Initial states are correct
console.log("\nInitial states:");
test("trafficLight starts in 'red'", () => {
  assertEqual(actors.trafficLight.getSnapshot().value, "red");
});

test("toggle starts in 'inactive'", () => {
  assertEqual(actors.toggle.getSnapshot().value, "inactive");
});

test("auth starts in 'idle'", () => {
  assertEqual(actors.auth.getSnapshot().value, "idle");
});

test("nested starts in {parent: 'child1'}", () => {
  assertEqual(actors.nested.getSnapshot().value, { parent: "child1" });
});

test("guarded starts in 'idle'", () => {
  assertEqual(actors.guarded.getSnapshot().value, "idle");
});

test("delayed starts in 'waiting'", () => {
  assertEqual(actors.delayed.getSnapshot().value, "waiting");
});

test("selfTransition starts in 'counter'", () => {
  assertEqual(actors.selfTransition.getSnapshot().value, "counter");
});

test("multiGuard starts in 'idle'", () => {
  assertEqual(actors.multiGuard.getSnapshot().value, "idle");
});

// 4. Transitions work
console.log("\nTransitions:");
test("trafficLight: red → TIMER → green", () => {
  actors.trafficLight.send({ type: "TIMER" });
  assertEqual(actors.trafficLight.getSnapshot().value, "green");
});

test("trafficLight: green → TIMER → yellow", () => {
  actors.trafficLight.send({ type: "TIMER" });
  assertEqual(actors.trafficLight.getSnapshot().value, "yellow");
});

test("trafficLight: yellow → TIMER → red (cycle)", () => {
  actors.trafficLight.send({ type: "TIMER" });
  assertEqual(actors.trafficLight.getSnapshot().value, "red");
});

test("toggle: inactive → TOGGLE → active", () => {
  actors.toggle.send({ type: "TOGGLE" });
  assertEqual(actors.toggle.getSnapshot().value, "active");
});

test("toggle: active → TOGGLE → inactive", () => {
  actors.toggle.send({ type: "TOGGLE" });
  assertEqual(actors.toggle.getSnapshot().value, "inactive");
});

test("nested: {parent: child1} → NEXT → {parent: child2}", () => {
  actors.nested.send({ type: "NEXT" });
  assertEqual(actors.nested.getSnapshot().value, { parent: "child2" });
});

test("nested: {parent: child2} → BACK → {parent: child1}", () => {
  actors.nested.send({ type: "BACK" });
  assertEqual(actors.nested.getSnapshot().value, { parent: "child1" });
});

test("selfTransition: counter → INCREMENT (stays in counter)", () => {
  actors.selfTransition.send({ type: "INCREMENT" });
  assertEqual(actors.selfTransition.getSnapshot().value, "counter");
});

test("selfTransition: counter → FINISH → done (final)", () => {
  actors.selfTransition.send({ type: "FINISH" });
  assertEqual(actors.selfTransition.getSnapshot().value, "done");
  assertEqual(actors.selfTransition.getSnapshot().status, "done");
});

// 5. Guarded transitions (all guards stub to true)
test("guarded: idle → SUBMIT → success (guard passes)", () => {
  actors.guarded.send({ type: "SUBMIT" });
  // With all guards returning true, first matching transition wins
  assertEqual(actors.guarded.getSnapshot().value, "success");
  assertEqual(actors.guarded.getSnapshot().status, "done");
});

// 6. Parallel state structure
console.log("\nParallel states:");
test("parallel starts with correct compound value", () => {
  const val = actors.parallel.getSnapshot().value;
  assert(val.dashboard, "Should have dashboard key");
  assert(val.dashboard.upload, "Should have upload region");
  assert(val.dashboard.mode, "Should have mode region");
  assertEqual(val.dashboard.upload, "uploadIdle");
  assertEqual(val.dashboard.mode, "light");
});

test("parallel: TOGGLE_MODE affects only mode region", () => {
  actors.parallel.send({ type: "TOGGLE_MODE" });
  const val = actors.parallel.getSnapshot().value;
  assertEqual(val.dashboard.upload, "uploadIdle");
  assertEqual(val.dashboard.mode, "dark");
});

test("parallel: START_UPLOAD affects only upload region", () => {
  actors.parallel.send({ type: "START_UPLOAD" });
  const val = actors.parallel.getSnapshot().value;
  assertEqual(val.dashboard.upload, "uploading");
  assertEqual(val.dashboard.mode, "dark");
});

// 7. Machine can() check
console.log("\nCapability checks:");
test("toggle: can(TOGGLE) in inactive", () => {
  // Reset by creating fresh actor
  const fresh = createActor(machines.toggle);
  fresh.start();
  assert(fresh.getSnapshot().can({ type: "TOGGLE" }), "Should accept TOGGLE");
});

test("toggle: cannot handle unknown event", () => {
  const fresh = createActor(machines.toggle);
  fresh.start();
  assert(!fresh.getSnapshot().can({ type: "UNKNOWN" }), "Should reject UNKNOWN");
});

// 8. Final states produce done status
console.log("\nFinal states:");
test("guarded reaches done status", () => {
  const fresh = createActor(machines.guarded);
  fresh.start();
  fresh.send({ type: "SUBMIT" });
  assertEqual(fresh.getSnapshot().status, "done");
});

// 9. Delayed transition detection
test("delayed machine has 'after' transition config", () => {
  // Just verify the machine was created and starts correctly
  const fresh = createActor(machines.delayed);
  fresh.start();
  assertEqual(fresh.getSnapshot().value, "waiting");
  // Send COMPLETE before timeout
  fresh.send({ type: "COMPLETE" });
  assertEqual(fresh.getSnapshot().value, "done");
});

// Cleanup: stop all actors
for (const actor of Object.values(actors)) {
  try { actor.stop(); } catch {}
}

// Summary
console.log(`\n${passed + failed} tests, ${passed} passed, ${failed} failed\n`);
if (failed > 0) {
  process.exit(1);
}
